development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { 'localhost:6379' } %>
  channel_prefix: central_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { 'localhost:6379' } %>
  channel_prefix: central_production
