# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "central_api"

development:
  <<: *common
  sasl_scram_username: <%= Rails.application.credentials.dig(:development, :kafka, :username) %>
  sasl_scram_password: <%= Rails.application.credentials.dig(:development, :kafka, :password) %>
  sasl_scram_mechanism: sha256
  ssl_ca_cert: "<%= Rails.application.credentials.dig(:kafka_cert) %>"
  brokers:
    - omnibus-01.srvs.cloudkafka.com:9094
    - omnibus-02.srvs.cloudkafka.com:9094
    - omnibus-03.srvs.cloudkafka.com:9094

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  sasl_scram_username: <%= Rails.application.credentials.dig(:development, :kafka, :username) %>
  sasl_scram_password: <%= Rails.application.credentials.dig(:development, :kafka, :password) %>
  sasl_scram_mechanism: sha256
  ssl_ca_cert: "<%= Rails.application.credentials.dig(:kafka_cert) %>"
  brokers:
    - deluxe-caboose-01.srvs.cloudkafka.com:9094
